Fiter\MinecraftBundle\Entity\Jobs:
    type: entity
    table: jobs_jobs
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        username:
            type: string
            length: 20
            fixed: false
            nullable: false
        experience:
            type: integer
            unsigned: false
            nullable: true
        level:
            type: integer
            unsigned: false
            nullable: true
        job:
            type: string
            length: 20
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
