fiter_minecraft_schematic:
    resource: "@FiterMinecraftSchematicBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/minecraft

BCCCronManagerBundle:
    resource: "@BCCCronManagerBundle/Resources/config/routing.xml"
    prefix:   /cron

fiter_backup:
    resource: "@FiterBackupBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/admin/backup

wikp_payment_mtgox:
    resource: "@WikpPaymentMtgoxBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/mtgox

fiter_minecraft_donation:
    resource: "@FiterMinecraftDonationBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/minecraft/donation

fiter_bitcoin:
    resource: "@FiterBitcoinBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

articulo_show_permanent:
    pattern:  /art/pl/{id}
    defaults: { _controller: FiterDefaultBundle:Articulo:show }
    requirements:
        _method:  GET|POST

fiter_minecraft:
    resource: "@FiterMinecraftBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

fiter_teamspeak:
    resource: "@FiterTeamspeakBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /{_locale}/sonata

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /{_locale}/sonata

my_yaml_i18n_routes:
    resource: "@FiterDefaultBundle/Resources/config/routing/i18n.yml"
    type: be_simple_i18n
    prefix:   /{_locale}

my_yaml_i18n_routes2:
    resource: "@FiterContactBundle/Resources/config/routing/i18n.yml"
    type: be_simple_i18n
    prefix:   /{_locale}

my_yaml_i18n_routes3:
    resource: "@FiterPollBundle/Resources/config/routing/i18n.yml"
    type: be_simple_i18n
    prefix:   /{_locale}

my_yaml_i18n_routes4:
    resource: "@FiterAdminBundle/Resources/config/routing/i18n.yml"
    type: be_simple_i18n
    prefix:   /{_locale}/admin

my_yaml_i18n_routes5:
    resource: "@FiterPhotoContestBundle/Resources/config/routing/i18n.yml"
    type: be_simple_i18n
    prefix:   /{_locale}/minecraft

#fiter_photo_contest:
#    resource: "@FiterPhotoContestBundle/Controller/"
#    type:     annotation
#    prefix:   /{_locale}/minecraft/

_imagine:
    resource: .
    type: imagine    

fiter_admin:
    resource: "@FiterAdminBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/admin

fos_user_security:
    resource: "@FiterUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FiterUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile/

fos_user_register:
    resource: "@FiterUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FiterUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FiterUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile

fos_comment_api:
    type: rest
    resource: "@FiterCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

fiter_comment:
    resource: "@FiterCommentBundle/Controller/"
    type:     annotation
    prefix:   /comment/
    defaults: { _locale: es }

fiter_default:
    resource: "@FiterDefaultBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults: { _locale: es }


fiter_sitemap:
    resource: "@FiterDefaultBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults: { _locale: es }

fiter_contact:
    resource: "@FiterContactBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults: { _locale: es }

# fiter_contact:
#     pattern:  /{_locale}/contacto
#     defaults: { _controller: FiterContactBundle:Page:contact }
#     requirements:
#         _method:  GET|POST

fiter_poll:
    resource: "@FiterPollBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

_portada:
    pattern:  /
    defaults: { _controller: FiterDefaultBundle:Default:index , _locale: es}

portada:
    pattern:  /{_locale}/
    defaults: { _controller: FiterDefaultBundle:Default:index, _locale: es }




