jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        #ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            #id: fos_user.user_provider.username
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path:     fos_user_security_login 
                check_path:     fos_user_security_check
            logout:
                path: fos_user_security_logout
            anonymous:    true
            
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
        - { path: ^/sonata/, role: ROLE_ADMIN }
        - { path: ^/(es|en|gl|ca)/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en|gl|ca)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en|gl|ca)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en|gl|ca)/admin/, role: ROLE_ADMIN }
        - { path: ^/(es|en|gl|ca)/bitcoin/, role: ROLE_ADMIN }
        - { path: ^/(es|en|gl|ca)/(categorias|categories)$, role: ROLE_ADMIN }
        - { path: ^/(es|en|gl|ca)/answer, role: ROLE_USER }
        - { path: ^/(es|en|gl|ca)/answergroup, role: ROLE_USER }
        - { path: ^/(es|en|gl|ca)/(perfil|profile), role: ROLE_USER }
        - { path: ^/(es|en|gl|ca)/(usuarios|users|usuaris), role: ROLE_USER }
        - { path: ^/(es|en|gl|ca)/(articulo|article)/(añadir|new), role: ROLE_USER }
        - { path: ^/(es|en|gl|ca)/poll/new, role: ROLE_USER }
        - { path: ^/(es|en|gl|ca)/teamspeak, role: ROLE_USER }


