## ArticuloController

admin_rss_articulo:
    locales:
        es: "/rss/articulos.{_format}"
        en: "/rss/articles.{_format}"
        gl: "/rss/artigos.{_format}"
    defaults: { _controller: FiterAdminBundle:Articulo:index  }
    requirements:
        _format:  rss

admin_articulo:
    locales:
        es: "/articulos"
        en: "/articles"
        gl: "/artigos"
    defaults: { _controller: FiterAdminBundle:Articulo:index }

admin_articulocategoria:
    locales:
        es: "/categoria/{slug}.{_format}"
        en: "/categorie/{slug}.{_format}"
        gl: "/categoria/{slug}.{_format}"
    defaults: { _controller: FiterAdminBundle:Articulo:indexCategoria , _format: html }
    requirements:
        _format:  html|rss

admin_articulousuario:
    locales:
        es: "/usuario/{nombre}.{_format}"
        en: "/user/{nombre}.{_format}"
        gl: "/usuario/{nombre}.{_format}"
    defaults: { _controller: FiterAdminBundle:Articulo:indexUsuario , _format: html }
    requirements:
        _format:  html|rss

admin_articulo_show:
    locales:
        es: "/articulo/{id}/{slug}/ver"
        en: "/article/{id}/{slug}/show"
        gl: "/artigo/{id}/{slug}/ver"
    defaults: { _controller: FiterAdminBundle:Articulo:show }

admin_articulo_new:
    locales:
        es: "/articulo/añadir"
        en: "/article/new"
        gl: "/artigo/engadir"
    defaults: { _controller: FiterAdminBundle:Articulo:new }

admin_articulo_create:
    locales:
        es: "/articulo/crear"
        en: "/article/create"
        gl: "/artigo/crear"
    defaults: { _controller: FiterAdminBundle:Articulo:create }

admin_articulo_edit:
    locales:
        es: "/articulo/{id}/{slug}/editar"
        en: "/article/{id}/{slug}/edit"
        gl: "/artigo/{id}/{slug}/editar"
    defaults: { _controller: FiterAdminBundle:Articulo:edit }

admin_articulo_update:
    locales:
        es: "/articulo/{id}/{slug}/actualizar"
        en: "/article/{id}/{slug}/update"
        gl: "/artigo/{id}/{slug}/actualizar"
    defaults: { _controller: FiterAdminBundle:Articulo:update }

admin_articulo_delete:
    locales:
        es: "/articulo/{id}/eliminar"
        en: "/article/{id}/delete"
        gl: "/artigo/{id}/eliminar"
    defaults: { _controller: FiterAdminBundle:Articulo:delete }

admin_articulobuscar:
    locales:
        es: "/articulo/buscar"
        en: "/article/search"
        gl: "/artigo/buscar"
    defaults: { _controller: FiterAdminBundle:Articulo:buscar }



## CategoriaController

admin_categoria:
    locales:
        es: "/categorias"
        en: "/categories"
        gl: "/categorias"
    defaults: { _controller: FiterAdminBundle:Categoria:index }

admin_categoria_show:
    locales:
        es: "/categorias/{id}/{slug}/ver"
        en: "/categories/{id}/{slug}/show"
        gl: "/categorias/{id}/{slug}/ver"
    defaults: { _controller: FiterAdminBundle:Categoria:show }

admin_categoria_new:
    locales:
        es: "/categorias/añadir"
        en: "/categories/new"
        gl: "/categorias/engadir"
    defaults: { _controller: FiterAdminBundle:Categoria:new }

## UsuarioController

admin_fos_user_profile_index:
    locales:
        es: "/usuarios"
        en: "/users"
        gl: "/usuarios"
    defaults: { _controller: FiterUserBundle:Profile:index  }

admin_fos_user_profile_show:
    locales:
        es: "/perfil"
        en: "/profile"
        gl: "/perfil"
    defaults: { _controller: FiterUserBundle:Profile:show  }

admin_fos_user_profile_edit:
    locales:
        es: "/perfil/editar"
        en: "/profile/edit"
        gl: "/perfil/editar"
    defaults: { _controller: FiterUserBundle:Profile:edit  }



## PollController

admin_poll:
    locales:
        es: "/encuestas"
        en: "/polls"
        gl: "/enquisas"
    defaults: { _controller: FiterAdminBundle:Poll:index }

admin_pollusuario:
    locales:
        es: "/encuestas/usuario/{nombre}"
        en: "/polls/user/{nombre}"
        gl: "/enquisas/usuario/{nombre}"
    defaults: { _controller: FiterAdminBundle:Poll:indexUsuario }

admin_poll_show:
    locales:  
        es: "/encuestas/{id}/ver"
        en: "/polls/{id}/show"
        gl: "/enquisas/{id}/ver"
    defaults: { _controller: FiterAdminBundle:Poll:show }

admin_poll_results:
    locales:  
        es: "/encuestas/{pollId}/resultados"
        en: "/polls/{pollId}/results" 
        gl: "/enquisas/{pollId}/resultados"
    defaults: { _controller: FiterAdminBundle:Poll:results }

admin_poll_new:
    locales:
        es: "/encuestas/añadir"
        en: "/polls/new"
        gl: "/enquisas/engadir"
    defaults: { _controller: FiterAdminBundle:Poll:new }

admin_poll_edit:
    locales:
        es: "/encuestas/{id}/editar"
        en: "/polls/{id}/edit"
        gl: "/enquisas/{id}/editar"
    defaults: { _controller: FiterAdminBundle:Poll:edit }
