<?php

namespace Fiter\PhotoContestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository{

	public function findAllPhotoActiveContestDQL($slug){
        $em = $this->getEntityManager('minecraft');
        $consulta = $em->createQuery('
            SELECT o FROM FiterPhotoContestBundle:Photo o
            JOIN o.contest c
            WHERE c.slug = :slug 
            
          
            ');
        $consulta->setParameter('slug', $slug);
        return $consulta;
    }
    public function findAllPhotoActiveContest($slug){
        return $this->findAllPhotoActiveContestDQL($slug)->getResult();
    }








    public function findAllPhotoContestUserDQL($contestId, $username){
        $em = $this->getEntityManager('minecraft');
        $consulta = $em->createQuery('
            SELECT o FROM FiterPhotoContestBundle:Photo o
            JOIN o.contest c
            WHERE c.id = :contestId 
            AND o.usuario = :username
            ');
        $consulta->setParameter('contestId', $contestId);
        $consulta->setParameter('username', $username);
        return $consulta;
    }
    public function findAllPhotoContestUser($contestId, $username){
        return $this->findAllPhotoContestUserDQL($contestId, $username)->getResult();
    }


}
