<?php

namespace Fiter\PhotoContestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository{

	public function findAllPhotoActiveContestDQL($slug){
        $em = $this->getEntityManager('minecraft');
        $consulta = $em->createQuery('
            SELECT o FROM FiterPhotoContestBundle:Photo o
            JOIN o.contest c
            WHERE c.slug = :slug 
            
          
            ');
        $consulta->setParameter('slug', $slug);
        return $consulta;
    }
    public function findAllPhotoActiveContest($slug){
        return $this->findAllPhotoActiveContestDQL($slug)->getResult();
    }

}
