<?php

namespace Fiter\PhotoContestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticuloRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoLikeRepository extends EntityRepository{
    public function checkCanLike($user,$photo){
        $em = $this->getEntityManager('minecraft');
        $query = $em->createQuery('
            SELECT COUNT(o.id) FROM FiterPhotoContestBundle:PhotoLike o
            WHERE o.usuario = :user
            AND o.photo = :photo
        ');
        $query->setParameter('user', $user);
        $query->setParameter('photo', $photo);
        //ladybug_dump($query->getSQL());
        return $query->getResult();
    }    
    public function findAllPhotoLikesUsuarioDQL($nombre){
        $em = $this->getEntityManager('minecraft');
        $consulta = $em->createQuery('
            SELECT o FROM FiterPhotoContestBundle:PhotoLike o
            WHERE o.usuario = :nombre
            AND o.notLike=0
            ');
        $consulta->setParameter('nombre', $nombre);
        return $consulta;
    }
    public function findAllPhotoLikesUsuario($nombre){
        return $this->findAllPhotoLikesUsuarioDQL($nombre)->getResult();
    }   
}
