<?php

namespace Fiter\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticuloRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloLikeRepository extends EntityRepository{
    public function checkCanLike($userId,$articulo){
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT COUNT(o.id) FROM FiterDefaultBundle:ArticuloLike o
            JOIN o.usuario a
            WHERE a.id = :id
            AND o.articulo = :articulo
        ');
        $query->setParameter('id', $userId);
        $query->setParameter('articulo', $articulo);
        //ladybug_dump($query->getSQL());
        return $query->getResult();
    }    
    public function findAllArticuloLikesUsuarioDQL($nombre){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT o FROM FiterDefaultBundle:ArticuloLike o
            JOIN o.usuario c
            WHERE c.username = :nombre
            AND o.notLike=0

            ');
        $consulta->setParameter('nombre', $nombre);
        return $consulta;
    }
    public function findAllArticuloLikesUsuario($nombre){
        return $this->findAllArticuloLikesUsuarioDQL($nombre)->getResult();
    }   
}
