<?php

namespace Fiter\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository{
    public function findMenuCategoriasConSubDQL(){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT c,s FROM FiterDefaultBundle:Categoria c
            JOIN c.subCategoria s
            ORDER BY c.visitas desc');
        return $consulta;
    }
    public function findMenuCategoriasConSub(){
        return $this->findMenuCategoriasDQL()->getResult();
    }
    public function findMenuCategoriasDQL(){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT c FROM FiterDefaultBundle:Categoria c
            ORDER BY c.visitas desc');
        return $consulta;
    }
    public function findMenuCategorias(){
        return $this->findMenuCategoriasDQL()->getResult();
    }
    public function findMenuCategoriasNoVaciasDQL(){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT c,a FROM FiterDefaultBundle:Categoria c
            JOIN c.articulos a
            WHERE a.activo=true
            ORDER BY c.visitas desc');
        return $consulta;
    }
    public function findMenuCategoriasNoVacias(){
        return $this->findMenuCategoriasNoVaciasDQL()->getResult();
    }
}
