<?php

namespace Fiter\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MedioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedioRepository extends EntityRepository{
    public function findTodosLosMediosDQL(){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT o FROM FiterDefaultBundle:Medio o
            ORDER BY o.likes DESC');
        return $consulta;
    }
    public function findTodosLosMedios(){
        return $this->findTodosLosMediosDQL()->getResult();
    }
    public function findTodosLosMediosActivosDQL(){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT o FROM FiterDefaultBundle:Medio o
            WHERE o.activo = true
            ORDER BY o.likes DESC');
        return $consulta;
    }
    public function findTodosLosMediosActivos(){
        return $this->findTodosLosMediosActivosDQL()->getResult();
    }
    public function findAllMediosCategoriaDQL($slug){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT o FROM FiterDefaultBundle:Medio o
            JOIN o.categoria c
            WHERE c.slug = :slug
            ORDER BY o.fechaPublicacion DESC
            ');
        $consulta->setParameter('slug', $slug);
        return $consulta;
    }
    public function findAllMediosCategoria($slug){
        return $this->findAllMediosCategoriaDQL($slug)->getResult();
    }
    
    public function findListaMasVistosDQL(){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT o FROM FiterDefaultBundle:Medio o
            ORDER BY o.visitas DESC')->setMaxResults(7);;
        return $consulta;
    }
    public function findListaMasVistos(){
        return $this->findListaMasVistosDQL()->getResult();
    }
    
    public function findListaMasValoradosDQL(){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT o FROM FiterDefaultBundle:Medio o
            ORDER BY o.likes DESC')->setMaxResults(7);;
        return $consulta;
    }
    public function findListaMasValorados(){
        return $this->findListaMasValoradosDQL()->getResult();
    }
    
    public function findListaActualizacionesDQL(){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT o FROM FiterDefaultBundle:Medio o
            WHERE o.fechaPublicacion != o.fechaActualizacion
            ORDER BY o.fechaActualizacion DESC')->setMaxResults(7);
        return $consulta;
    }
    public function findListaActualizaciones(){
        return $this->findListaActualizacionesDQL()->getResult();
    }
    
    public function findListaRelacionadosDQL($slug){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT o FROM FiterDefaultBundle:Medio o
            JOIN o.categoria c
            WHERE c.slug = :slug
            ORDER BY o.fechaPublicacion DESC
            ');
        $consulta->setParameter('slug', $slug)->setMaxResults(7);
        return $consulta;
    }
    public function findListaRelacionados($slug){
        if($slug=="inicio")
            return $this->findListaMasVistosDQL()->getResult();
        else
            return $this->findListaRelacionadosDQL($slug)->getResult();
        
        
    }
    
    
    
    
    
    
    
    public function findAllMediosUsuarioDQL($nombre){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT o,u FROM FiterDefaultBundle:Medio o
            JOIN o.usuario c
            JOIN o.categoria u
            WHERE c.username = :nombre
            ORDER BY o.fechaPublicacion DESC
            ');
        $consulta->setParameter('nombre', $nombre);
        return $consulta;
    }
    public function findAllMediosUsuario($nombre){
        return $this->findAllMediosUsuarioDQL($nombre)->getResult();
    }
    
    
    
    
}
