<?php

namespace Fiter\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoriaRepository extends EntityRepository
{
}
