<?php

namespace Fiter\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListaYoutubeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoYoutubeRepository extends EntityRepository{
    
}
