<?php

namespace Fiter\MinecraftBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthmeRepository extends EntityRepository{

    public function findOrdenadosDQL(){
        $em = $this->getEntityManager('minecraft');
        $consulta = $em->createQuery('
            SELECT o FROM FiterMinecraftBundle:Authme o
            ORDER BY o.lastlogin DESC');
        return $consulta;
    }
    public function findOrdenados(){
        return $this->findOrdenadosDQL()->getResult();
    }
}
