<?php

namespace Fiter\MinecraftSchematicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchematicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchematicRepository extends EntityRepository
{
}
