<?php

namespace Fiter\MinecraftSchematicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchematicRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchematicLikeRepository extends EntityRepository{
    public function checkCanLike($userId,$schematic){
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT COUNT(o.id) FROM FiterMinecraftSchematicBundle:SchematicLike o
            JOIN o.usuario a
            WHERE a.id = :id
            AND o.schematic = :schematic
        ');
        $query->setParameter('id', $userId);
        $query->setParameter('schematic', $schematic);
        //ladybug_dump($query->getSQL());
        return $query->getResult();
    }    
    public function findAllSchematicLikesUsuarioDQL($nombre){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT o FROM FiterDefaultBundle:ArticuloLike o
            JOIN o.usuario c
            WHERE c.username = :nombre
            AND o.notLike=0

            ');
        $consulta->setParameter('nombre', $nombre);
        return $consulta;
    }
    public function findAllSchematicLikesUsuario($nombre){
        return $this->findAllSchematicLikesUsuarioDQL($nombre)->getResult();
    }   
}
